In [1]:
#Proprietary content. ©Great Learning. All Rights Reserved. Unauthorized use or distribution prohibited

In [2]:
#Creating Single dimensional array

In [2]:
import numpy as np
print(np.cos(np.pi))
print(np.sin(3.5))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))
arr=[10,12,14,16,18]
print(np.mean(arr))

-1.0
-0.35078322768961984
1.1
5.2
14.0


In [3]:
vec = np.array([2,4,6])
print(vec)
mat = np.array([[1,23,4],[4,6,7],[2,5,7]])
print('')
print(mat,end = '\n\n')
print(mat.transpose(1,0),end = '\n\n')
print(mat.transpose(0,1),end = '\n\n')
print(mat.transpose(),end = '\n\n')
print(mat.T)

[2 4 6]

[[ 1 23  4]
 [ 4  6  7]
 [ 2  5  7]]

[[ 1  4  2]
 [23  6  5]
 [ 4  7  7]]

[[ 1 23  4]
 [ 4  6  7]
 [ 2  5  7]]

[[ 1  4  2]
 [23  6  5]
 [ 4  7  7]]

[[ 1  4  2]
 [23  6  5]
 [ 4  7  7]]


In [8]:
vec1 = np.arange(0,15) #Here we specify step size, default start value is 0
print(vec1.T)
#the transpose of a vector is same as the vector
# numpy type range stores all values in the actual range, exclusive of ending value, considering the step size.
vec2 = np.arange(0,15,2)
print(vec2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]


In [9]:
# Start & End point are both inclusive, here we specify no of samples, default sample size value is 50
vec3 = np.linspace(0,5,10)
# 3rd argument is for the no of points required in the array: Here: 0, 5/9, 2*(5/9) so on..
print(vec3)
# print(np.linalg.solve(vec3,b)) ****ASK
print(np.unique(vec3))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [10]:
print(vec3.reshape(5,2))
vec3Reshaped= vec3.reshape(5,2)
#size of array must be equal to no of rows*no of columns
print('')
print(vec3Reshaped)
print(vec3)

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [11]:
mat2= np.zeros([5,3])
print(mat2)
mat3 = np.ones([3,5])
print(mat3)
mat4 = np.eye(5)
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
vec5 = np.arange(1,6)
vec6 = np.arange(4,9)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[4 5 6 7 8]
[ 5  7  9 11 13]
[ 4 10 18 28 40]
[1.         0.5        0.33333333 0.25       0.2       ]
[2.         2.23606798 2.44948974 2.64575131 2.82842712]


In [13]:
print(mat)
print(vec,end="\n\n")
product = np.matmul(mat,vec)
print(product)

[[ 1 23  4]
 [ 4  6  7]
 [ 2  5  7]]
[2 4 6]

[118  74  66]


In [14]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[2. 4. 6.]

[[-0.02473498  0.49823322 -0.48409894]
 [ 0.04946996  0.00353357 -0.03180212]
 [-0.02826855 -0.14487633  0.30388693]]


In [61]:
vec7 = np.array(['Blue','red','orange','blue','black','red',67])
print(vec7)
print(np.unique(vec7))

['Blue' 'red' 'orange' 'blue' 'black' 'red' '67']
['67' 'Blue' 'black' 'blue' 'orange' 'red']


In [116]:
#using numpy to generate samples of random variable
rand_mat = np.random.rand(5,5) #Uniform RANDOM VARIABLE
print(rand_mat,end ="\n\n")
rand_mat2 = np.random.randn(10,5) #Standard Normal RANDOM VARIABLE
print(rand_mat2)

[[0.85840513 0.08586148 0.55945213 0.78337791 0.44545085]
 [0.51734569 0.03111443 0.14335149 0.72794449 0.07053324]
 [0.02515458 0.85136086 0.20155196 0.73992709 0.99938765]
 [0.80961635 0.79093238 0.43730138 0.50502797 0.84646417]
 [0.23474233 0.2977469  0.51222727 0.0323368  0.73722777]]

[[-0.11137367  0.69012564 -1.74782791  1.28213771  1.36824068]
 [-0.20503279 -1.67338563 -0.2871208   0.65532334  0.30379411]
 [ 1.27695171 -1.31391711 -0.76067035 -2.45356077 -1.63408309]
 [ 1.35786961  0.77167543 -1.05669183  0.22881299 -1.39788467]
 [-0.59913998  1.45398607 -0.455615   -1.09091672 -0.77416807]
 [-0.62778666 -1.20068816 -2.7190126   0.46965773  0.18798058]
 [-2.10068459 -0.50511965  0.496365   -1.26621087 -0.4677581 ]
 [ 0.50541768 -0.60773346 -0.20220114 -1.41187134 -0.87719288]
 [-0.72848539 -0.85131115  1.14078214 -0.00325783  1.69617476]
 [ 1.1947779  -0.38623294  0.26120672  1.78109476 -1.73308698]]


In [117]:
print(np.mean(rand_mat),end="\n\n")
print(np.std(rand_mat2,0)) #calculating std deviation of an array along the given axis

0.48975369285688614

[1.04442857 0.96644452 1.06058102 1.26483701 1.13950306]


In [118]:
print(np.min(rand_mat),end="\n\n")
print(np.max(rand_mat2))

0.025154580462710352

1.781094761523998


In [119]:
arr=[10,12,14,16,18]
print(np.mean(arr,0))#mean(arr,axis): axis is 1 : calculated along the row
print(np.mean(arr))#By default, mean for all elements is calculated

14.0
14.0


In [120]:
import numpy as np

n2=np.array([[10,20,30,40],[40,30,20,10]])
print(n2,'   ', np.mean(n2,1))

[[10 20 30 40]
 [40 30 20 10]]     [25. 25.]


In [6]:
type(n2)

numpy.ndarray

In [7]:
#Extracting elements

In [8]:
n1

array([10, 20, 30, 40])

In [9]:
n1[0]

10

In [10]:
n1[1:3]

array([20, 30])

In [11]:
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [12]:
n2[0,0]

10

In [13]:
n2[0]

array([10, 20, 30, 40])

In [14]:
n2[1,3]

10

In [15]:
np.zeros

<function numpy.zeros>

In [16]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [17]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
#np.arange

In [34]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#np.full

In [38]:
import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [ ]:
#np.randit

In [1]:
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([80, 75, 49, 71, 49])

In [3]:
n1.shape

(5,)

In [4]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [ ]:
#NumPy Shape

In [5]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [ ]:
#Numpy Sum

In [13]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2])

100

In [14]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [15]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [17]:
#NumPy comparison

In [18]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.equal(n1,n2)

array([ True, False, False])

In [19]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.array_equal(n1,n2)

False

In [20]:
#Joining Arrays

In [32]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [34]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [7]:
import numpy as np
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [3]:
n1=n1+1
n1

array([11, 21, 31])

In [18]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [22]:
np.intersect1d(n1,n2)

array([50, 60])

In [23]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [12]:
#numpy math functions

In [17]:
import numpy as np
n1=np.array([1,5,3,100,4,48])
np.std(n1)

36.59424666377065

In [7]:
import numpy as np
n8 = np.array([10,20,30])
n7 = np.array([40,50,60])
np.column_stack((n7,n8))

array([[40, 10],
       [50, 20],
       [60, 30]])

In [93]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[4:9],end="\n\n")
print(rand_vec[6])        

[ 1.67731833 -0.90383639  0.72385707  0.40069689  0.50197536 -0.57814983
  0.86906799 -1.81168721 -0.8176829  -0.66681572 -0.18463446 -2.520076
 -0.32695804  0.69655016 -0.28795507 -2.06883389  0.62546913  0.51705837
  0.07929796]
[ 0.50197536 -0.57814983  0.86906799 -1.81168721 -0.8176829 ]

0.8690679874703477


In [94]:
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)]) #prints elements at index locations 1,3,6,9,12 of rand_vec

[ 0  3  6  9 12]
[ 1.67731833  0.40069689  0.86906799 -0.66681572 -0.32695804]


In [114]:
#About matrices
print(rand_mat,end="\n\n")
print(rand_mat[1][2])
print(rand_mat[1,2])

[[3.         3.         3.         0.82478449 0.35787912]
 [3.         3.         3.         0.         0.        ]
 [0.71813042 0.11318698 0.01384619 0.         0.        ]
 [0.75874228 0.07377686 0.68854211 0.5833194  0.63156838]
 [0.07202974 0.18092709 0.06398626 0.99910927 0.69325564]]

3.0
3.0


In [115]:
print(rand_mat[0:2,1:3])

[[3. 3.]
 [3. 3.]]


In [121]:
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
print('')
rand_vec[3:5] = [9,8]
print(rand_vec)

[ 1.67731833 -0.90383639  0.72385707  9.          8.         -0.57814983
  0.86906799 -1.81168721 -0.8176829  -0.66681572 -0.18463446 -2.520076
 -0.32695804  0.69655016 -0.28795507 -2.06883389  0.62546913  0.51705837
  0.07929796]

[ 1.67731833 -0.90383639  0.72385707  4.          4.         -0.57814983
  0.86906799 -1.81168721 -0.8176829  -0.66681572 -0.18463446 -2.520076
 -0.32695804  0.69655016 -0.28795507 -2.06883389  0.62546913  0.51705837
  0.07929796]

[ 1.67731833 -0.90383639  0.72385707  9.          8.         -0.57814983
  0.86906799 -1.81168721 -0.8176829  -0.66681572 -0.18463446 -2.520076
 -0.32695804  0.69655016 -0.28795507 -2.06883389  0.62546913  0.51705837
  0.07929796]


In [122]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat,end="\n\n")
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)

[[0.85840513 0.08586148 0.55945213 0.78337791 0.44545085]
 [0.51734569 0.03111443 0.14335149 0.72794449 0.07053324]
 [0.02515458 0.85136086 0.20155196 0.73992709 0.99938765]
 [0.80961635 0.79093238 0.43730138 0.50502797 0.84646417]
 [0.23474233 0.2977469  0.51222727 0.0323368  0.73722777]]

[[0.85840513 0.08586148 0.55945213 0.78337791 0.44545085]
 [0.51734569 0.03111443 0.14335149 0.         0.        ]
 [0.02515458 0.85136086 0.20155196 0.         0.        ]
 [0.80961635 0.79093238 0.43730138 0.50502797 0.84646417]
 [0.23474233 0.2977469  0.51222727 0.0323368  0.73722777]]

[[0.85840513 0.08586148 0.55945213]
 [0.51734569 0.03111443 0.14335149]]


In [124]:

sub_mat[:]= 3 #means every single value of the array
print('')
print(sub_mat,end ="\n\n")
print(rand_mat) #by assigning a sub-mat some other value, it also changes the original matrix


[[3. 3. 3.]
 [3. 3. 3.]]

[[3.         3.         3.         0.78337791 0.44545085]
 [3.         3.         3.         0.         0.        ]
 [0.02515458 0.85136086 0.20155196 0.         0.        ]
 [0.80961635 0.79093238 0.43730138 0.50502797 0.84646417]
 [0.23474233 0.2977469  0.51222727 0.0323368  0.73722777]]


In [129]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2,end ="\n\n")
print(rand_mat) 

[[99. 99. 99.]
 [99. 99. 99.]]

[[3.         3.         3.         0.78337791 0.44545085]
 [3.         3.         3.         0.         0.        ]
 [0.02515458 0.85136086 0.20155196 0.         0.        ]
 [0.80961635 0.79093238 0.43730138 0.50502797 0.84646417]
 [0.23474233 0.2977469  0.51222727 0.0323368  0.73722777]]


In [131]:
vec = np.arange(10,20)
print(vec)
vec2 = vec[np.arange(0,10,3)]
print(vec2)

[10 11 12 13 14 15 16 17 18 19]
[10 13 16 19]


In [132]:
demo_array = np.arange(10,21)



subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [17]:
#Addition of numPy arrays
nu1 = np.array([10,20])
nu2 = np.array([30,40])
np.sum([nu1,nu2])

100

In [19]:
np.sum([nu1,nu2],axis=1) #axis: 1 for rows, 0 for columnwise addition

array([30, 70])

In [23]:
num = np.array([50,60,70])
num = num*2
num

array([100, 120, 140])

In [24]:
np.mean(num)

120.0

In [25]:
np.std(num)

16.32993161855452

In [26]:
np.median(num)

120.0

In [28]:
np.save('my_numpy',num)

In [29]:
num1= np.load('my_numpy.npy')
num1

array([100, 120, 140])