In [1]:
import numpy as np


In [2]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
n4=np.zeros((6,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
n5 = np.full((3,3),(8))
n5

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [5]:
n6 = np.full((6,8),(4))
n6


array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])

In [7]:
n7 = np.arange(10,49)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [8]:
n8 = np.arange(3,90,3)
n8

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [13]:
n9 = np.random.randint(4,68,10)
n9

array([26, 37, 60, 19,  9, 21, 59, 46, 63, 59])

In [16]:
n10 = np.array([[7,8,9],[2,3,4]])
n10.shape = (3,2)
n10

array([[7, 8],
       [9, 2],
       [3, 4]])

In [7]:
import pandas as pd
dataset= pd.read_excel('GDP_Dataset.xlsx')
dataset

S.No              Country  Population  Yearly_Change  Land_Area  \
0       1                China  1421021791           0.39    9388211   
1       2                India  1338676785           0.99    2973190   
2       3        United States   325084756           0.59    9147420   
3       4            Indonesia   264650963           1.07    1811570   
4       5             Pakistan   207906209           2.00     770880   
..    ...                  ...         ...            ...        ...   
167   181              Vanuatu       77001           2.42      12190   
168   183             Barbados       58058           0.12        430   
169   187  Sao Tome & Principe       33671           1.91        960   
170   188                Samoa       17808           0.67       2830   
171   189          Saint Lucia       11370           0.46        610   

     Population_Density  Migrants_Net  Median_Age  Urban_Population  \
0            151.362362       -348399          38              61.0   
1            450.249323       -532687          28              35.0   
2             35.538409        954806          38              83.0   
3            146.089283        -98955          30              56.0   
4            269.699835       -233379          23              35.0   
..                  ...           ...         ...               ...   
167            6.316735           120          21              24.0   
168          135.018605           -79          40              31.0   
169           35.073958         -1680          19              74.0   
170            6.292580         -2803          22              18.0   
171           18.639344             0          34              19.0   

     World_Share_in_Population        GDP  GDP_per_Capita  Share_of_World_GDP  \
0                        18.47  12238.000        8.612113               15.12   
1                        17.70   2651.000        1.980314                3.28   
2                         4.25  19485.000       59.938215               24.08   
3                         3.51   1015.000        3.835240                1.25   
4                         2.83    305.000        1.467008                0.38   
..                         ...        ...             ...                 ...   
167                       0.00      0.863       11.207647                0.00   
168                       0.00      4.670       80.436805                0.01   
169                       0.00      0.393       11.671765                0.00   
170                       0.00      0.841       47.225966                0.00   
171                       0.00      1.740      153.034301                0.00   

         Status  
0    Developing  
1    Developing  
2     Developed  
3    Developing  
4    Developing  
..          ...  
167  Developing  
168  Developing  
169  Developing  
170  Developing  
171  Developing  

[172 rows x 14 columns]

In [22]:
dataset.shape[1] #total no of columns
dataset.info
col = dataset.columns
col
dsList = list(dataset)
dsList
dataset.count()

S.No                         172
Country                      172
Population                   172
Yearly_Change                172
Land_Area                    172
Population_Density           172
Migrants_Net                 172
Median_Age                   172
Urban_Population             168
World_Share_in_Population    172
GDP                          172
GDP_per_Capita               172
Share_of_World_GDP           172
Status                       172
dtype: int64

In [30]:
dsGroupedData = dataset.groupby(by='Status')
dsGroupedData.describe()

S.No                                                         \
            count       mean        std  min    25%   50%     75%    max   
Status                                                                     
Developed    34.0  92.676471  52.097066  3.0  43.00  95.5  125.50  180.0   
Developing  138.0  91.014493  54.086844  1.0  44.25  91.0  136.75  189.0   

           Population                ... GDP_per_Capita              \
                count          mean  ...            75%         max   
Status                               ...                              
Developed        34.0  2.914449e+07  ...      60.513086  256.638652   
Developing      138.0  4.575749e+07  ...      10.773471  153.034301   

           Share_of_World_GDP                                                 \
                        count      mean       std   min   25%    50%     75%   
Status                                                                         
Developed                34.0  1.638824  4.209974  0.02  0.09  0.360  1.4250   
Developing              138.0  0.308841  1.352005  0.00  0.01  0.035  0.1475   

                   
              max  
Status             
Developed   24.08  
Developing  15.12  

[2 rows x 96 columns]

In [31]:
dataset.describe()

S.No    Population  Yearly_Change     Land_Area  \
count  172.000000  1.720000e+02     172.000000  1.720000e+02   
mean    91.343023  4.247352e+07       1.252558  7.365638e+05   
std     53.553207  1.532222e+08       1.084430  1.939793e+06   
min      1.000000  1.137000e+04      -1.350000  3.000000e+01   
25%     43.750000  2.211687e+06       0.435000  3.034000e+04   
50%     92.500000  8.637852e+06       1.155000  1.556800e+05   
75%    136.250000  3.118956e+07       2.085000  5.673325e+05   
max    189.000000  1.421022e+09       3.840000  1.637687e+07   

       Population_Density   Migrants_Net  Median_Age  Urban_Population  \
count          172.000000     172.000000  172.000000        168.000000   
mean           256.511581    8183.203488   30.366279         59.119048   
std           1100.876812  117854.957213    9.187432         22.014913   
min              0.951880 -532687.000000   15.000000         13.000000   
25%             22.706984  -10755.250000   22.000000         43.000000   
50%             64.974567   -1364.500000   30.000000         59.000000   
75%            135.131229   12298.250000   39.000000         78.000000   
max          11146.433333  954806.000000   48.000000         98.000000   

       World_Share_in_Population           GDP  GDP_per_Capita  \
count                 172.000000    172.000000      172.000000   
mean                    0.571453    462.496203       21.722370   
std                     2.007700   1839.549604       36.585698   
min                     0.000000      0.393000        0.292786   
25%                     0.040000     12.257500        2.054639   
50%                     0.130000     41.090000        7.160957   
75%                     0.420000    238.750000       23.511084   
max                    18.470000  19485.000000      256.638652   

       Share_of_World_GDP  
count          172.000000  
mean             0.571744  
std              2.273114  
min              0.000000  
25%              0.020000  
50%              0.050000  
75%              0.295000  
max             24.080000

In [39]:
# dsDataPop = dataset.groupby(by='Population')
sum = dataset['Population'].sum()
print(sum)

7305446192


In [43]:
maxMage = dataset['Median_Age'].max()
print(maxMage) #How to find country corresponding to this max number value: Ans: Japan

48


In [49]:
PerPop90 = sum*0.9
num = dataset['Urban_Population']
num #For how many countries' urban population is more than 90% of the total population.
# CntryCnt = dataset.loc[num]>PerPop90

0      61.0
1      35.0
2      83.0
3      56.0
4      35.0
       ... 
167    24.0
168    31.0
169    74.0
170    18.0
171    19.0
Name: Urban_Population, Length: 172, dtype: float64

In [51]:
pdList = dataset['Population_Density'].describe()
pdList #Which are the top 3 countries in terms of High Population Density?

count      172.000000
mean       256.511581
std       1100.876812
min          0.951880
25%         22.706984
50%         64.974567
75%        135.131229
max      11146.433333
Name: Population_Density, dtype: float64

In [57]:
# how many countries have a GDP greater than the GDP of India?
GdpIndia= print(dataset.loc[[1],['GDP']])
dataset['GDP']

      GDP
1  2651.0


0      12238.000
1       2651.000
2      19485.000
3       1015.000
4        305.000
         ...    
167        0.863
168        4.670
169        0.393
170        0.841
171        1.740
Name: GDP, Length: 172, dtype: float64

In [58]:
c=0
def countryCount(GdpIndia):
    if(dataset['GDP']>GdpIndia)
    c=c+1
    return c

print(countryCount(GdpIndia))

SyntaxError: invalid syntax (<ipython-input-58-0b8b2af33632>, line 3)

In [59]:
# GDP per capita of the country which has a population greater than 10 crores and GDP equal to $250 Billion?
def calGdpPerCapita():
    if(dataset['Population']>100000000 and dataset['GDP']=250000000000)